### PR TITLE
Cw8

### PR DESCRIPTION
**Pull request by TattCherr**
Dear Alexander Anatoljevich, 
following a tradition, herewith I am sending you the next batch of answers for your consideration & checks. 
Best regards/ Grüße aus Deutschland,
Take care in Odessa, 
Tatyana

### CODE REVIEW

**Review by oleksandrblazhko — APPROVED** [review]
Dear Tatyana
Your solution gets 7 points!
Total score = 76
Remember Odessa!

**Comment by TattCherr** [comment]
Dear Alexander Anatoljevitch,
Are you sleeping at all? :)
Thanks a lot for checking.
On the weekend I will try to bring the issue till 80 points, if it is ok
for you. 80 points sound much better than 76.
Odessa is forever in our hearts. I am  even a Ukrainian citizen with a flat
and city registration in Odessa:).

Take care!

Tatyana

**Comment by oleksandrblazhko** [comment]
Dear Tatyana!
A woman is always a woman! And it's wonderful!
80 points is still the European D-level.
But the European C-level is 85 points.
Are you ready to complete the C-level?
If you are ready, then do Lab #10.

Alexander

P.S.
The successful woman in German economic company with an Odessa flat is a good prospect! :)

**Comment by TattCherr** [comment]
The truth is, nobody in Germany cares about your points and where you got
your diploma. It is a proven statement.
The knowledge matters. In our case it is more a personal ego and no wish to
waste one point ;).

To the rest i will better react in a private email :).

Best regards,

Tatyana

**Pull request merged**
